#!/bin/sh
set -e

mkdir -p target
for file in *.asm; do
echo $file
    file=$file | sed 's/.asm//'
    echo $file
    llvm-mc --triple=riscv32 --assemble --filetype=obj $file -o target/$file
    ld.lld link.ld target/$file -o target/$file
    llvm-objcopy -O binary target/$file target/$file
done