#!/bin/sh
set -e

llvm-mc --triple=riscv32 --assemble --filetype=obj std.s -o target/std

mkdir -p target
for file in *.asm; do
    file="$(echo $file | sed 's/.asm//')"
    llvm-mc --triple=riscv32 --assemble --filetype=obj $file.asm -o target/$file
    ld.lld link.ld target/$file target/std -o target/$file
    llvm-objcopy -O binary target/$file target/$file
done